import {
  dividendTaxOfficialSources,
  fhsaOfficialSources,
  mortgageOfficialSources,
  retirementOfficialSources,
  rrspOfficialSources,
  tfsaOfficialSources,
} from './officialSources';

export const topicHubs = {
  tfsa: {
    path: '/topics/tfsa',
    label: 'TFSA',
    title: 'TFSA Hub for Canadians',
    description: 'Use this TFSA hub to understand contribution room, tax-free growth, account priority, investing mistakes, and when a TFSA may or may not fit.',
    eyebrow: 'Registered account hub',
    intro: 'The TFSA is powerful because withdrawals are tax-free and contribution room can return, but the details matter. Start here if you need to confirm room, compare TFSA against RRSP or FHSA, or decide whether investing inside a TFSA fits your timeline.',
    startHere: [
      'Confirm contribution room against CRA before making a real deposit.',
      'Use the TFSA calculator when room and growth are the main question.',
      'Use the account-decision tool when an RRSP deduction or FHSA home goal is competing for the same dollar.',
    ],
    misunderstood: [
      'Withdrawals do not create same-year room unless you already had unused room available.',
      'A TFSA is an account type, not an investment. Cash, ETFs, GICs, and stocks behave differently inside it.',
      'Tax-free growth does not remove investment risk, foreign withholding tax nuance, or contribution-room penalties.',
    ],
    calculators: [
      ['TFSA calculator', '/tools/tfsa-calculator'],
      ['Account decision tool', '/tools/account-decision-tool'],
      ['Compound interest calculator', '/tools/compound-interest-calculator'],
    ],
    guides: [
      ['TFSA contribution room Canada 2026', '/blog/tfsa-contribution-room-canada-2026'],
      ['TFSA vs RRSP in Canada', '/blog/tfsa-vs-rrsp-canada-2026'],
      ['TFSA investing mistakes', '/blog/tfsa-investing-mistakes-canada'],
      ['Best ETFs for a TFSA', '/blog/best-etfs-for-tfsa-canada-2026'],
    ],
    sources: tfsaOfficialSources,
  },
  rrsp: {
    path: '/topics/rrsp',
    label: 'RRSP',
    title: 'RRSP Hub for Canadians',
    description: 'Compare RRSP deductions, refund use, contribution deadlines, retirement tax tradeoffs, and TFSA/FHSA alternatives.',
    eyebrow: 'Retirement account hub',
    intro: 'The RRSP is not just a refund machine. It works best when the deduction, refund use, retirement tax rate, and competing account choices are considered together.',
    startHere: [
      'Confirm deduction room on your CRA Notice of Assessment before contributing.',
      'Estimate the refund, then decide whether it will be reinvested, used for debt, or saved elsewhere.',
      'Compare against TFSA or FHSA if your current tax rate, home goal, or flexibility needs make the decision unclear.',
    ],
    misunderstood: [
      'The refund is not free money. It reflects tax deferred until withdrawal.',
      'A high refund can still be weak if withdrawals happen at a similar or higher tax rate.',
      'RRSP room and cash available are separate constraints; both matter.',
    ],
    calculators: [
      ['RRSP calculator', '/tools/rrsp-calculator'],
      ['Account decision tool', '/tools/account-decision-tool'],
      ['Income tax calculator', '/tools/income-tax-calculator'],
    ],
    guides: [
      ['RRSP deadline Canada 2026', '/blog/rrsp-deadline-canada-2026'],
      ['TFSA vs RRSP in Canada', '/blog/tfsa-vs-rrsp-canada-2026'],
      ['TFSA vs RRSP vs FHSA', '/blog/tfsa-vs-rrsp-vs-fhsa-canada'],
      ['RRSP accounts in Canada', '/blog/best-rrsp-accounts-canada'],
    ],
    sources: rrspOfficialSources,
  },
  fhsa: {
    path: '/topics/fhsa',
    label: 'FHSA',
    title: 'FHSA Hub for First-Time Home Buyers',
    description: 'Plan FHSA eligibility, room, tax savings, transfers, withdrawals, and whether FHSA should come before TFSA or RRSP.',
    eyebrow: 'First-home account hub',
    intro: 'The FHSA can combine a deduction with a tax-free qualifying home withdrawal, but only when the eligibility, timeline, and home-buying goal line up.',
    startHere: [
      'Check eligibility and first-time home buyer status before opening or contributing.',
      'Use the FHSA calculator to estimate tax savings, room, and projected balance.',
      'Compare FHSA against RRSP Home Buyers Plan and TFSA if the down payment timeline is uncertain.',
    ],
    misunderstood: [
      'Unused participation room is limited; opening timing can matter.',
      'A non-qualifying withdrawal can become taxable, changing the whole strategy.',
      'The FHSA is less useful if a first-home purchase is unlikely or too far outside the account timeline.',
    ],
    calculators: [
      ['FHSA calculator', '/tools/fhsa-calculator'],
      ['Account decision tool', '/tools/account-decision-tool'],
      ['Mortgage affordability calculator', '/tools/mortgage-affordability-calculator'],
    ],
    guides: [
      ['FHSA rules Canada 2026', '/blog/fhsa-rules-canada-2026'],
      ['FHSA calculator guide', '/blog/fhsa-calculator-canada-2026'],
      ['FHSA vs RRSP for down payment', '/blog/fhsa-vs-rrsp-down-payment-canada-2026'],
      ['TFSA vs RRSP vs FHSA', '/blog/tfsa-vs-rrsp-vs-fhsa-canada'],
    ],
    sources: fhsaOfficialSources,
  },
  dividends: {
    path: '/topics/dividends',
    label: 'Dividend investing',
    title: 'Canadian Dividend Investing Hub',
    description: 'Understand dividend ETFs, income targets, DRIP, covered calls, account location, and tax tradeoffs in Canada.',
    eyebrow: 'Investing income hub',
    intro: 'Dividend income can be useful, but yield alone is a weak decision tool. This hub focuses on sustainability, tax location, total return, and the tradeoff between income today and growth tomorrow.',
    startHere: [
      'Use the dividend calculator to translate a monthly income target into required capital.',
      'Read ETF and DRIP guides before chasing yield.',
      'Check taxable-account treatment when dividends sit outside TFSA, RRSP, or FHSA.',
    ],
    misunderstood: [
      'A higher yield can signal more risk, slower growth, or return-of-capital complexity.',
      'DRIP can increase units but does not remove tax reporting in taxable accounts.',
      'Covered-call ETFs can trade upside for cash flow and may not suit long time horizons.',
    ],
    calculators: [
      ['Dividend calculator', '/tools/dividend-calculator'],
      ['Compound interest calculator', '/tools/compound-interest-calculator'],
      ['Investment tracker', '/tools/investment-tracker'],
    ],
    guides: [
      ['How to earn $500/month from dividend ETFs', '/blog/500-month-dividend-canada'],
      ['Best Canadian dividend ETFs 2026', '/blog/best-canadian-dividend-etfs-2026'],
      ['What is a dividend ETF?', '/blog/what-is-a-dividend-etf-canada'],
      ['DRIP strategy Canada', '/blog/drip-strategy-canada'],
      ['Covered call ETFs explained', '/blog/covered-call-etfs-canada-explained'],
    ],
    sources: dividendTaxOfficialSources,
  },
  mortgages: {
    path: '/topics/mortgages',
    label: 'Mortgages',
    title: 'Canadian Mortgage Planning Hub',
    description: 'Compare mortgage payments, affordability, stress-test context, down-payment planning, rent-vs-buy, and payoff tradeoffs.',
    eyebrow: 'Home-buying hub',
    intro: 'Mortgage planning is not only the monthly payment. A strong plan checks down payment, closing costs, stress-test pressure, amortization tradeoffs, and whether the home still fits the rest of the budget.',
    startHere: [
      'Use affordability before payment math if income, debts, or stress-test room are uncertain.',
      'Use the mortgage calculator when price, down payment, and rate are already known.',
      'Use FHSA planning before deciding how much registered money to commit toward the down payment.',
    ],
    misunderstood: [
      'Approval room and comfort room are not the same thing.',
      'A longer amortization can lower monthly payment while increasing total interest.',
      'Closing costs, land transfer tax, insurance, and maintenance can matter as much as the rate.',
    ],
    calculators: [
      ['Mortgage affordability calculator', '/tools/mortgage-affordability-calculator'],
      ['Mortgage calculator', '/tools/mortgage-calculator'],
      ['Rent vs buy calculator', '/tools/rent-vs-buy'],
      ['FHSA calculator', '/tools/fhsa-calculator'],
    ],
    guides: [
      ['Pay off mortgage faster in Canada', '/blog/pay-off-mortgage-faster-canada'],
      ['FHSA vs RRSP for a down payment', '/blog/fhsa-vs-rrsp-down-payment-canada-2026'],
      ['FHSA rules Canada 2026', '/blog/fhsa-rules-canada-2026'],
    ],
    sources: mortgageOfficialSources,
  },
  retirement: {
    path: '/topics/retirement',
    label: 'Retirement',
    title: 'Canadian Retirement Planning Hub',
    description: 'Plan RRSP, CPP, OAS, FIRE assumptions, tax tradeoffs, withdrawal context, and retirement-income decisions.',
    eyebrow: 'Retirement planning hub',
    intro: 'Retirement planning gets clearer when RRSP tax deferral, TFSA flexibility, CPP/OAS timing, and portfolio assumptions are tested together instead of separately.',
    startHere: [
      'Use RRSP and FIRE calculators for scenario planning, not prediction.',
      'Check CPP/OAS dates and benefit rules against official government pages.',
      'Compare retirement income after tax, not only account balances.',
    ],
    misunderstood: [
      'A large RRSP balance can create later taxable income and benefit-recovery issues.',
      'CPP and OAS timing decisions depend on longevity, cash-flow needs, and other income sources.',
      'FIRE assumptions can break when returns, inflation, housing, or health costs differ from the model.',
    ],
    calculators: [
      ['RRSP calculator', '/tools/rrsp-calculator'],
      ['CPP/OAS estimator', '/tools/cpp-oas-estimator'],
      ['FIRE calculator', '/tools/fire-calculator'],
      ['Compound interest calculator', '/tools/compound-interest-calculator'],
    ],
    guides: [
      ['CPP payment dates 2026', '/blog/cpp-payment-dates-2026'],
      ['OAS payment dates 2026', '/blog/oas-payment-dates-2026'],
      ['RRSP deadline Canada 2026', '/blog/rrsp-deadline-canada-2026'],
      ['TFSA vs RRSP in Canada', '/blog/tfsa-vs-rrsp-canada-2026'],
    ],
    sources: retirementOfficialSources,
  },
};

export const topicHubList = Object.values(topicHubs);
